### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by francepack** [Wil-Huffman/mod_0_assesment#1]
@Wil-Huffman 
Overall, nice work. There are a few things to address to perfect your work here.

Very nice work in your `variables.rb` file!

Overall, nice work with your object modeling. A few things to look at here:
- [x] In your `A` file, because you are modeling a particular tRex, `averageSizes` may not apply to a single tRex. For the array data type, it is best to think of them as collections that can be added to, or taken away from, rather than a set of options to be selected from. Revise this attribute to hold some kind of collection further describing the tRex.
- [x] Similar feedback for your `B` file- I am not sure `averageAge` or `averageHeight` help you describe Wil the developer. Try to think of string attributes that steer away from potentially being integers, and describe the specific person, Wil.

A piece of general feedback: Keep working towards commit message consistency! You can check out your log [here](https://github.com/Wil-Huffman/mod_0_assesment/commits/main). I suggest avoiding past tense, though you will see that commit message format out there. Most important is being consistent within a project.

**Comment by Wil-Huffman** [comment]
Boxes checked.
